name: 'Node.js Release Manager'
description: 'Automates version management and release process for Node.js projects'

inputs:
  release-type:
    description: 'Type of release (major, minor, patch)'
    required: false
    default: 'minor'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RELEASE_TYPE: ${{ inputs.release-type }}