name: 'Node.js Release Manager'
description: 'Automates version management and release process for Node.js projects'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  release-type:
    description: 'Type of release (major, minor, patch)'
    required: false
    default: 'minor'
runs:
  using: 'docker'
  image: 'Dockerfile'